sudo: required
services:
  - docker

before_install:
  - docker build -t isaacheist/react-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run isaacheist/react-tests npm test -- --coverage

after_success:
  - docker build -t isaacheist/complex-client ./client
  - docker build -t isaacheist/complex-nginx ./nginx
  - docker build -t isaacheist/complex-server ./server
  - docker build -t isaacheist/complex-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push isaacheist/complex-client
  - docker push isaacheist/complex-nginx
  - docker push isaacheist/complex-server
  - docker push isaacheist/complex-worker